const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  fs.mkdirSync('artifacts', {recursive: true});
  const browser = await chromium.launch({channel:'msedge', headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[], failed=[];
  page.on('pageerror', e=>errors.push(e.message));
  page.on('response', r=>{if(r.status()>=400) failed.push(`${r.status()} ${r.url()}`)});
  await page.goto(process.env.SITE_URL || 'http://127.0.0.1:8080', {waitUntil:'networkidle'});
  assert.equal(await page.evaluate(()=>window.scrollY),0,'Page must not jump on load');
  for(const width of [320,390,768,1024,1440,1920]) {
    await page.setViewportSize({width,height:1000});
    await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow at ${width}`);
    await page.screenshot({path:`artifacts/portfolio-${width}.jpg`,type:'jpeg',quality:80});
  }
  await page.locator('#motion-toggle').click();
  assert.equal(await page.locator('#motion-toggle').getAttribute('aria-pressed'),'true');
  assert.ok(await page.evaluate(()=>document.documentElement.classList.contains('motion-paused')));
  await page.locator('#motion-toggle').click();
  assert.equal(await page.locator('#motion-toggle').getAttribute('aria-pressed'),'false');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(() => document.getElementById('motion-toggle').hidden);
  assert.ok(await page.locator('#motion-toggle').isHidden());
  assert.equal(await page.locator('#home').evaluate(el=>getComputedStyle(el,'::after').animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#mobile-toggle-btn').click();
  assert.equal(await page.locator('#mobile-toggle-btn').getAttribute('aria-expanded'),'true');
  await page.locator('#nav-menu a[href="#skills"]').click();
  assert.equal(await page.locator('#mobile-toggle-btn').getAttribute('aria-expanded'),'false');
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-open-resume]').first().click();
  assert.equal(await page.locator('#resume-modal').evaluate(el=>el.inert),false);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#resume-modal').evaluate(el=>el.inert),true);
  await page.locator('[data-open-resume]').first().click();
  await page.pdf({path:'artifacts/resume.pdf',format:'A4'});
  await page.keyboard.press('Escape');
  await page.locator('#open-terminal-btn').click();
  await page.locator('#terminal-input').fill('help');
  await page.locator('#terminal-input').press('Enter');
  assert.ok((await page.locator('#terminal-output').innerText()).includes('skills'));
  await page.keyboard.press('Escape');
  await page.locator('#btn-next-project').click();
  assert.match(await page.locator('#project-slide-indicator').innerText(),/02/);
  await page.locator('#btn-toggle-view').click();
  assert.ok(await page.locator('#projects-slider-stage').evaluate(el=>el.classList.contains('grid-mode')));
  await page.locator('#dir-search-input').fill('Terraform');
  assert.ok(await page.locator('.dir-card').count()>0);
  await page.locator('#dir-search-input').fill('no-such-tool-xyz');
  assert.equal(await page.locator('.dir-card').count(),0);
  await page.locator('#dir-search-input').fill('');
  await page.locator('#linux-search-input').fill('nonexistent-topic-xyz');
  assert.equal(await page.locator('.linux-card:visible').count(),0);
  await page.locator('#linux-search-input').fill('');
  await page.locator('.scope-chip[data-scope="k8s-migration"]').click();
  await page.locator('.scope-chip[data-cloud="Azure"]').click();
  await page.locator('#scale-slider').fill('3');
  assert.match(await page.locator('#est-deliverables').innerText(),/Kubernetes|EKS/);
  assert.ok(decodeURIComponent(await page.locator('#btn-calc-whatsapp').getAttribute('href')).includes('Azure'));
  await page.locator('#btn-next-devsec').click();
  assert.match(await page.locator('#devsec-slide-badge').innerText(),/02/);
  await page.locator('#btn-toggle-devsec-mode').click();
  assert.ok(await page.locator('#devsec-slider-stage').evaluate(el=>el.classList.contains('grid-mode')));
  await page.locator('#architectures').scrollIntoViewIfNeeded();
  await page.waitForFunction(()=>document.querySelector('#project-mermaid-diagram svg'),{},{timeout:45000});
  const options=await page.locator('#arch-project-select option').evaluateAll(nodes=>nodes.map(x=>x.value));
  for(const option of options) {
    await page.locator('#arch-project-select').selectOption(option);
    await page.waitForFunction(()=>!document.querySelector('#project-mermaid-diagram').hasAttribute('aria-busy'));
    assert.ok(await page.locator('#project-mermaid-diagram svg').count(),`Diagram ${option}`);
  }
  await page.locator('#c2c-run-btn').click();
  await page.waitForFunction(()=>document.querySelector('#c2c-run-label').textContent.includes('Replay'),{},{timeout:15000});
  await page.locator('#contact-name').fill('Test Visitor');
  await page.locator('#contact-email').fill('test@example.com');
  await page.locator('#contact-message').fill('Local verification only.');
  await page.locator('#consultation-form button[type=submit]').click();
  assert.match(await page.locator('#contact-status').innerText(),/Send it there/);
  assert.equal(await page.locator('#contact-message').inputValue(),'Local verification only.');
  console.log(JSON.stringify({errors,failed,architectureVariants:options.length,checks:'Responsive 320–1920, pause and reduced motion, initial scroll, navigation, dialogs, terminal, resume print, projects, directory, all architecture diagrams, deployment simulation, contact draft'},null,2));
  assert.deepEqual(errors,[]);
  assert.deepEqual(failed,[]);
  const noJS = await browser.newPage({javaScriptEnabled:false});
  await noJS.goto(process.env.SITE_URL || 'http://127.0.0.1:8080');
  assert.ok(await noJS.locator('#hero-heading').isVisible());
  assert.ok(await noJS.locator('#about .section-header').isVisible());
  assert.equal(await noJS.locator('#about .section-header').evaluate(el=>getComputedStyle(el).opacity),'1');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
